# .drone.yml
kind: pipeline
name: default

steps:
- name: build
  image: kura2i/drone-test-img:latest
  privileged: false
  commands:
    - ./install.sh /usr/local/
    - echo "hoge" | /usr/local/bin/cowsay
    
