# .drone.yml
kind: pipeline
name: default

steps:
- name: build
  image: ubuntu:18.04
  privileged: true
  commands:
    - apt-get install libgetopt-complete-perl 
    - ./install.sh /usr/local/
    - echo "hoge" | /usr/local/bin/cowsay
    
